config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  root 'products#index'
  resources :orders do
    member do
      get :confirm
    end
  end
  resources :order_items
  resources :products
  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match '/login' => redirect("/auth/twitter"), as: :login, via: :get
  match '/logout' => "sessions#destroy", as: :logout, via: :get

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :user
  belongs_to :address
  
  def total
    order_items.map(&:subtotal).sum
    # alternatively
    # order_items.to_a.sum { |item| item.subtotal }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :confirm]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end
  
  def confirm
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params.merge(status: "submitted"))
        format.html { redirect_to confirm_order_path(@order), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :status, :address_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/confirm.html.erb
<h1>Thank you</h1>

<p>Your order with <%= @order.order_items.count %> items for a total of <%= @order.total %> has been submitted!</p>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<%= form_for @order do |f| %>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user_id %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Order Total:</th>
    <td><%= print_price @order.total %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Stock</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
    <th>Remove</th>
  </tr>
  
  <% @order.order_items.each do |item| %>
  <tr>
    <td><%= image_tag "products/#{item.product.image_url}" %></td>
    <td><%= item.product.title %></td>
    <td><%= link_to item.quantity, edit_order_item_path(item) %></td>
    <td><%= print_stock item.product.stock, item.quantity %></td>
    <td><%= item.product.price %></td>
    <td><%= print_price item.subtotal %></td>
    <td><%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= @order.user.name if @order.user %></td>
  </tr>
  <% end %>
  
  <tr>
    <th>Shipping To:</th>
    <td>
      <%= f.select :address_id, current_user.addresses.collect{|a| [a.to_s, a.id]} %></br>
      <%= link_to "Add an address", new_address_path %>
    </td>
  </tr>
  
  <tr>
    <th>Submit Order:</th>
    <td><%= f.submit "Submit order" %></td>
  </tr>
</table>

<% end %>
<p><%= link_to "Empty Cart", @order, method: :delete, data: { confirm: "Are you sure>" } %></p>